"use client";

import { Inter } from "next/font/google";
import "./styles/globals.scss";
import { ThemeContextProvider } from "@/lib/context";
import { useThemeContext } from "@/lib/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AppWrapper = ({ children }) => {
  const { theme } = useThemeContext();
  return (
    <div className={`${theme === "dark" ? "theme--dark" : "theme--light"}`}>
      {children}
    </div>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={inter.className}>
          <AppWrapper>{children}</AppWrapper>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
